eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: project-routes
          uri: lb://PROJECT
          predicates:
            - Path=/project/**
          filters:
            - PrefixPath=/api
        - id: backlog-routes
          uri: lb://BACKLOG
          predicates:
            - Path=/state/**,/type/**,/backlogitem/**,/card/**,/checkitem/**
          filters:
            - PrefixPath=/api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/agilefox-spring-microservices
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: spring-client

server:
  port: 8085

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG

