eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: project-routes
          uri: lb://PROJECT
          predicates:
            - Path=/project/**
          filters:
            - PrefixPath=/api
        - id: state-routes
          uri: lb://BACKLOG
          predicates:
            - Path=/state/**,/type/**,/backlogitem/**
          filters:
            - PrefixPath=/api
server:
  port: 8085


