volumes:
  volume_name:
    name: backlog_volume
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./backlog_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=changemeinprod
      - POSTGRES_USER=backlog
      - POSTGRES_DB=backlogdb