volumes:
  volume_name:
    name: backlog_volume
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./backlog_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}