services:
  keycloak-db:
    image: postgres:15
    ports:
      - "5434:5432"
    container_name: keycloak-db
    environment:
      - POSTGRES_PASSWORD=changemeinprod
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloakdb
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-network


  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: changemeinprod
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: >
      start-dev --import-realm
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    volumes:
      - ./myrealm.json:/opt/keycloak/data/import/myrealm.json
    networks:
      - keycloak-network

volumes:
  keycloak-db-data:

networks:
  keycloak-network: